---
- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: Add two IPv4 DNS server addresses
    nmcli:
      conn_name: "{{ ansible_default_ipv4.alias }}"
      type: ethernet
      dns4:
      - 8.8.8.8
      - 8.8.4.4
      state: present

  - name: restart network service
    shell: " nmcli connection up '{{ ansible_default_ipv4.alias }}' " 
...
 
